replicaCount: 1

deploy:
  app:
    register: msa-register
    payment: msa-payment
    product: msa-product
    statistics: msa-statistics
    nodejs: front-nodejs
    nginx: front-nginx
    mariadb: mariadb

  port:
    register: 8000
    payment: 8001
    product: 8002
    statistics: 8003
    nodejs: 3000
    nginx: 80
    mariadb: 3306

maraidb:
  name: mariadb-service

url:
  ip: 3.36.70.177
  port:
    frontend: 30010
    REGIST_SRV_URL: 30100
    PAYMENT_SRV_URL: 30300
    PRODUCT_SRV_URL: 30400
    STATISTICS_SRV_URL: 30500

secret:
  mariadb:
    name: db-secret

imgs:
  REGIST_IMG: yoon741/arm64-register-service:latest
  PAYMENT_IMG: ashashrain/arm64-payment-service:latest
  PARKING_IMG: docdker/arm64-parking-service:v6
  STATISTICS_IMG: snicuz0588/arm64-statistics-service:latest
  NODEJS_IMG: dangdang42/arm64-nodejs:latest
  NGINX_IMG: dangdang42/arm64-nginx:latest
